### ISSUE TITLE
Marketing y Comercialización

### ISSUE THREAD

**Issue by gastonperez26** [gastonperez26/cypmuestra2022#5]

**Comment by Exe0712** [comment]
[Marketing.docx](https://github.com/gastonperez26/cypmuestra2022/files/10171836/Marketing.docx)

**Comment by Exe0712** [comment]
Profe adjuntamos nuestra parte del trabajo. El archivo esta creado por:
Gomez Fabricio.
Vera Andrea.
Valdez Exequiel.
